### ISSUE TITLE
help

### ISSUE THREAD

**Issue by chenxqiyu** [kelvindev15/Kotlin2PlantUML#344]
![image](https://github.com/kelvindev15/Kotlin2PlantUML/assets/10222853/a52102cc-c195-4f58-a5cf-9926b9d962d2)

java -jar kotlin2plantuml.jar kotlin.CharCodeKt -cp filename.jar

Exception in thread "main" java.lang.UnsupportedOperationException: Packages and file facades are not yet supported in Kotlin reflection. Meanwhile please use Java reflection to inspect this class: class kotlin.CharCodeKt
        at kotlin.reflect.jvm.internal.KClassImpl.reportUnresolvedClass(KClassImpl.kt:310)
        at kotlin.reflect.jvm.internal.KClassImpl.access$reportUnresolvedClass(KClassImpl.kt:44)
        at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:56)
        at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:48)
        at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:93)
        at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
        at kotlin.reflect.jvm.internal.KClassImpl$Data.getDescriptor(KClassImpl.kt:48)
        at kotlin.reflect.jvm.internal.KClassImpl$Data$supertypes$2.invoke(KClassImpl.kt:125)
        at kotlin.reflect.jvm.internal.KClassImpl$Data$supertypes$2.invoke(KClassImpl.kt:124)
        at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:93)
        at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
        at kotlin.reflect.jvm.internal.KClassImpl$Data.getSupertypes(KClassImpl.kt:124)
        at kotlin.reflect.jvm.internal.KClassImpl.getSupertypes(KClassImpl.kt:254)
        at kotlin.reflect.full.KClasses.getSuperclasses(KClasses.kt:184)
        at io.github.kelvindev15.kotlin2plantuml.plantuml.ClassHierarchy.<init>(ClassHierarchy.kt:37)
        at io.github.kelvindev15.kotlin2plantuml.plantuml.ClassDiagram.<init>(ClassDiagram.kt:14)
        at io.github.kelvindev15.kotlin2plantuml.MainKt.main(Main.kt:103)

**Comment by kelvin-olaiya** [comment]
I suspect that the issue is with the version of Kotlin your jar was compiled with
